Repository Ucoll/fend-landingpage, pull requests merged in 2022-02, with the labels that each got.

#2 Feature/ Buttons AslanSN
  README.md
  package-lock.json
  package.json
  src/img/how-to.png
  src/img/icons/dislike/DislikeAwaken.png
  src/img/icons/dislike/DislikeSlept.png
  src/img/icons/dislike/WOW 2.png
  src/img/icons/favorite/GoldenFavorite.png
  src/img/icons/favorite/ImageFavorite.png
  src/img/icons/like/LikeAwaken.png
  src/img/icons/like/LikeSlept.png
  src/img/icons/like/WOW 1.png
  src/img/icons/ucoll-logo/UCollLogoVertical.png
  src/img/rigo-baby.jpg
  src/js/component/Buttons/Collapse/Collapse.css
  src/js/component/Buttons/Collapse/Collapse.css.map
  src/js/component/Buttons/Collapse/Collapse.jsx
  src/js/component/Buttons/Collapse/Collapse.scss
  src/js/component/Buttons/Comment/Comment.jsx
  src/js/component/Buttons/Dislike/DislikeButton.jsx
  src/js/component/Buttons/Dislike/DislikeButtonStyle.scss
  src/js/component/Buttons/Favorite/Favorite.jsx
  src/js/component/Buttons/Favorite/Favorite.scss
  src/js/component/Buttons/Feed/FeedClass.jsx
  src/js/component/Buttons/Feed/FeedCollege.jsx
  src/js/component/Buttons/Feed/FeedGlobal.jsx
  src/js/component/Buttons/Like/LikeButton.jsx
  src/js/component/Buttons/Like/LikeButtonStyle.scss
  src/js/component/Buttons/NewPost/NewPost.jsx
  src/js/component/Buttons/NewPostButtons/NewPostDocument.jsx
  src/js/component/Buttons/NewPostButtons/NewPostLink.jsx
  src/js/component/Buttons/NewPostButtons/NewPostSurvey.jsx
  src/js/component/Buttons/NewPostButtons/NewPostText.jsx
  src/js/component/Buttons/NewPostButtons/NewPostVideo.jsx
  src/js/component/Buttons/SearchBar/SearchBar.css
  src/js/component/Buttons/SearchBar/SearchBar.css.map
  src/js/component/Buttons/SearchBar/SearchBar.jsx
  src/js/component/Buttons/SearchBar/SearchBar.scss
  src/js/component/Buttons/Settings/Settings.css
  src/js/component/Buttons/Settings/Settings.css.map
  src/js/component/Buttons/Settings/Settings.jsx
  src/js/component/Buttons/Settings/Settings.scss
  src/js/component/Buttons/Share/Share.jsx
  src/js/component/Buttons/Thread/Thread.css
  src/js/component/Buttons/Thread/Thread.css.map
  src/js/component/Buttons/Thread/Thread.jsx
  src/js/component/Buttons/Thread/Thread.scss
  src/js/component/Buttons/UCollLogo/UCollLogo.jsx
  src/js/component/Buttons/UCollLogo/UCollLogo.scss
  src/js/layout.js
  src/js/views/demo.js
  src/js/views/home.js
  src/styles/index.css
  webpack.common.js
Labels: feature, ready-to-merge

#8 Fix/fix favorite button
  README.md
  package-lock.json
  package.json
  src/img/how-to.png
  src/img/icons/dislike/DislikeAwaken.png
  src/img/icons/dislike/DislikeSlept.png
  src/img/icons/dislike/WOW 2.png
  src/img/icons/like/LikeAwaken.png
  src/img/icons/like/LikeSlept.png
  src/img/icons/like/WOW 1.png
  src/img/icons/ucoll-logo/UCollLogoVertical.png
  src/img/rigo-baby.jpg
  src/js/component/Buttons/Collapse/Collapse.css
  src/js/component/Buttons/Collapse/Collapse.css.map
  src/js/component/Buttons/Collapse/Collapse.jsx
  src/js/component/Buttons/Collapse/Collapse.scss
  src/js/component/Buttons/Comment/Comment.jsx
  src/js/component/Buttons/Dislike/DislikeButton.jsx
  src/js/component/Buttons/Dislike/DislikeButtonStyle.scss
  src/js/component/Buttons/Favorite/Favorite.jsx
  src/js/component/Buttons/Favorite/Favorite.scss
  src/js/component/Buttons/Feed/FeedClass.jsx
  src/js/component/Buttons/Feed/FeedCollege.jsx
  src/js/component/Buttons/Feed/FeedGlobal.jsx
  src/js/component/Buttons/Like/LikeButton.jsx
  src/js/component/Buttons/Like/LikeButtonStyle.scss
  src/js/component/Buttons/NewPost/NewPost.jsx
  src/js/component/Buttons/NewPostButtons/NewPostDocument.jsx
  src/js/component/Buttons/NewPostButtons/NewPostLink.jsx
  src/js/component/Buttons/NewPostButtons/NewPostSurvey.jsx
  src/js/component/Buttons/NewPostButtons/NewPostText.jsx
  src/js/component/Buttons/NewPostButtons/NewPostVideo.jsx
  src/js/component/Buttons/SearchBar/SearchBar.css
  src/js/component/Buttons/SearchBar/SearchBar.css.map
  src/js/component/Buttons/SearchBar/SearchBar.jsx
  src/js/component/Buttons/SearchBar/SearchBar.scss
  src/js/component/Buttons/Settings/Settings.css
  src/js/component/Buttons/Settings/Settings.css.map
  src/js/component/Buttons/Settings/Settings.jsx
  src/js/component/Buttons/Settings/Settings.scss
  src/js/component/Buttons/Share/Share.jsx
  src/js/component/Buttons/Thread/Thread.css
  src/js/component/Buttons/Thread/Thread.css.map
  src/js/component/Buttons/Thread/Thread.jsx
  src/js/component/Buttons/Thread/Thread.scss
  src/js/component/Buttons/UCollLogo/UCollLogo.jsx
  src/js/component/Buttons/UCollLogo/UCollLogo.scss
  src/js/layout.js
  src/js/views/demo.js
  src/js/views/home.js
  src/styles/index.css
  webpack.common.js
Labels: bug, ready-to-merge

#7 Fix: Refactored the Like and Dislike buttons
  src/img/icons/dislike/DislikeAwaken.png
  src/img/icons/dislike/DislikeSlept.png
  src/img/icons/dislike/WOW 2.png
  src/img/icons/like/LikeAwaken.png
  src/img/icons/like/LikeSlept.png
  src/img/icons/like/WOW 1.png
  src/js/component/Buttons/Dislike/DislikeButton.jsx
  src/js/component/Buttons/Dislike/DislikeButtonStyle.scss
  src/js/component/Buttons/Like/LikeButton.jsx
  src/js/component/Buttons/Like/LikeButtonStyle.scss
  src/js/component/Buttons/Like/LikeButtons.jsx
  src/js/component/Buttons/Like/LikeButtonsStyle.scss
  src/js/layout.js
Labels: bug, ready-to-merge

#6 Tokens Component
  src/img/icons/favorite/GoldenFavorite.png
  src/img/icons/favorite/OutFavorite.png
  src/js/component/Buttons/Favorite/Favorite.jsx
  src/js/component/Buttons/Favorite/Favorite.scss
  src/js/component/Buttons/Favorite/FavoriteGolden/FavoriteGolden.jsx
  src/js/component/Buttons/Favorite/FavoriteOut/FavoriteOut.jsx
  src/js/component/Buttons/UCollLogo/UCollLogo.jsx
  src/static/Fonts/FanwoodText-Regular.ttf
  src/static/Fonts/Poppins-Regular.ttf
  src/static/Fonts/Quicksand-VariableFont_wght.ttf
  src/static/Tokens.ts
  src/static/icons/ucoll-logo/UCollLogoVertical.png
Labels: feature, ready-to-merge

#5 Feature/Coll component
  src/js/component/Buttons/Collapse/Collapse.css
  src/js/component/Buttons/Collapse/Collapse.css.map
  src/js/component/Buttons/Favorite/Favorite.jsx
  src/js/component/Buttons/Favorite/Favorite.scss
  src/js/component/Buttons/Like/LikeButtons.jsx
  src/js/component/Buttons/Like/LikeButtonsStyle.scss
  src/js/component/Buttons/SearchBar/SearchBar.css
  src/js/component/Buttons/SearchBar/SearchBar.css.map
  src/js/component/Buttons/Settings/Settings.css
  src/js/component/Buttons/Thread/Thread.css
  src/js/component/Buttons/Thread/Thread.css.map
  src/js/component/Buttons/Thread/Thread.jsx
  src/js/component/Buttons/Thread/Thread.scss
  src/js/component/Buttons/UCollLogo/UCollLogo.css
  src/js/component/Buttons/UCollLogo/UCollLogo.css.map
  src/js/component/Coll/Coll.jsx
  src/js/component/Coll/Coll.scss
  src/js/layout.js
  src/styles/index.css
Labels: feature, work-in-progress, dont-merge

#12 Fix/fix coll size
  src/js/component/Coll/Coll.scss
Labels: feature, ready-to-merge

#11 Profile Side Menu Component
  README.md
  src/js/component/Buttons/Dislike/DislikeButtonStyle.css
  src/js/component/Buttons/Dislike/DislikeButtonStyle.css.map
  src/js/component/Buttons/Favorite/FavoriteGolden/FavoriteGolden.jsx
  src/js/component/Buttons/Favorite/FavoriteOut/FavoriteOut.jsx
  src/js/component/Buttons/Like/LikeButtonStyle.css
  src/js/component/Buttons/Like/LikeButtonStyle.css.map
  src/js/component/Coll/Coll.css
  src/js/component/Coll/Coll.css.map
  src/js/component/HoverCollapsable/ProfileSideMenu.jsx
  src/js/component/HoverCollapsable/ProfileSideMenu.scss
Labels: feature, ready-to-merge

#14 Feature: Navbar
  src/js/component/Buttons/SearchBar/SearchBar.css
  src/js/component/Buttons/SearchBar/SearchBar.css.map
  src/js/component/Buttons/SearchBar/SearchBar.jsx
  src/js/component/Buttons/SearchBar/SearchBar.scss
  src/js/component/Buttons/UCollLogo/UCollLogo.jsx
  src/js/component/Buttons/UCollLogo/UCollLogo.scss
  src/js/component/Navbar/Navbar.jsx
  src/js/component/Navbar/Navbar.scss
  src/js/layout.js
  src/styles/index.css
Labels: feature, ready-to-merge

#15 FEATURE: Resource Button
  src/js/component/Resources/Resource.jsx
  src/js/component/Resources/Resource.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#16 FEATURE: Resources Side Menu
  src/js/component/Resources/Resource.jsx
  src/js/component/Resources/Resource.scss
  src/js/component/Resources/ResourcesMenu.jsx
  src/js/component/Resources/ResourcesMenu.scss
  src/js/layout.js
  src/styles/index.css
Labels: feature, ready-to-merge

#17 FEATURE: Compressed Coll
  src/js/component/Coll/Coll.css
  src/js/component/Coll/Coll.css.map
  src/js/component/Coll/CompressedColl.jsx
  src/js/component/Coll/CompressedColl.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#18 FEATURE: New Photo Coll
  src/js/component/Buttons/NewPostButtons/NewPostPhoto.jsx
  src/js/index.js
  src/styles/index.scss
Labels: feature, ready-to-merge

#19 Feature: Profile Buttons
  src/js/component/Buttons/MyColls/MyColls.jsx
  src/js/component/Buttons/MyColls/MyColls.scss
  src/js/component/Buttons/ProfileFavorite/ProfileFavorite.jsx
  src/js/component/Buttons/ProfileFavorite/ProfileFavorite.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#23 Feature: Profile Edit Button
  src/js/component/Buttons/ProfileEditButton/ProfileEditButton.jsx
  src/js/component/Buttons/ProfileEditButton/ProfileEditButton.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#22 Feature/interest-tag
  src/js/component/Tags/InterestTag.jsx
  src/js/component/Tags/InterestTag.svg
  src/js/component/Tags/InterestTagStyled.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#24 Feature: Profile Career and Description
  src/js/component/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/component/ProfileCareerDescription/ProfileCareerDescription.scss
  src/js/layout.js
Labels: feature, ready-to-merge

#29 Feature: Profile User Info Component
  src/js/component/Profile-PageComponents/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/component/Profile-PageComponents/ProfileClasses/ProfileClasses.jsx
  src/js/component/Profile-PageComponents/ProfileClasses/ProfileClasses.scss
  src/js/component/Profile-PageComponents/ProfileUserInfo/ProfileUserInfo.jsx
  src/js/component/Profile-PageComponents/ProfileUserInfo/ProfileUserInfo.scss
Labels: feature, ready-to-merge

#30 Feature: Profile Biography
  src/js/component/Profile-PageComponents/ProfileBiography/ProfileBiography.jsx
  src/js/component/Profile-PageComponents/ProfileBiography/ProfileBiography.scss
  src/js/component/Profile-PageComponents/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/layout.js
Labels: feature, ready-to-merge

#32 Feature: Profile Social Media
  src/js/component/Profile-PageComponents/ProfileBiography/ProfileBiography.jsx
  src/js/component/Profile-PageComponents/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/component/Profile-PageComponents/SocialMedia/SocialMedia.jsx
  src/js/component/Profile-PageComponents/SocialMedia/SocialMedia.scss
  src/js/component/Profile-PageComponents/SocialMedia/SocialMediaText.jsx
  src/js/component/Profile-PageComponents/SocialMedia/SocialMediaText.scss
  src/js/views/Profile/ScrapProfileView/ScrapProfile.jsx
Labels: feature, ready-to-merge
