Repository Ucoll/fend-landingpage, pull requests merged in 2022-03, with the labels that each got.

#35 Feature/landing page view
  src/js/component/HomePageComponents/Coll/Coll.jsx
  src/js/component/HomePageComponents/Coll/Coll.scss
  src/js/component/HomePageComponents/Coll/CompressedColl/CompressedColl.jsx
  src/js/component/HomePageComponents/Coll/CompressedColl/CompressedColl.scss
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ClassesComponent/Classes.jsx
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ClassesComponent/ClassesStyles.scss
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ColleaguesSideMenu.jsx
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ColleaguesSideMenuStyles.scss
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/Ellipse.png
  src/js/component/HomePageComponents/Menus/ProfileSideMenu/ProfileSideMenu.jsx
  src/js/component/HomePageComponents/Menus/ProfileSideMenu/ProfileSideMenu.scss
  src/js/component/HomePageComponents/Menus/Resources/Components/Resource.jsx
  src/js/component/HomePageComponents/Menus/Resources/Components/Resource.scss
  src/js/component/HomePageComponents/Menus/Resources/ResourcesMenu.jsx
  src/js/component/HomePageComponents/Menus/Resources/ResourcesMenu.scss
  src/js/component/LandingPageComponents/Buttons/CreateAccountButton/CreateAccountButton.jsx
  src/js/component/LandingPageComponents/Buttons/CreateAccountButton/CreateAccountButtonStyles.scss
  src/js/component/LandingPageComponents/Buttons/LogInButton/LogInButton.jsx
  src/js/component/LandingPageComponents/Buttons/LogInButton/LogInButtonStyles.scss
  src/js/component/LandingPageComponents/LogInCard/LoginCard.jsx
  src/js/component/LandingPageComponents/LogInCard/LoginCardStyles.scss
  src/js/component/ProfilePageComponents/Buttons/ProfileFavorite/ProfileFavorite.jsx
  src/js/component/ProfilePageComponents/Buttons/ProfileFavorite/ProfileFavorite.scss
  src/js/component/ProfilePageComponents/Cover/Cover Background.jpg
  src/js/component/ProfilePageComponents/Cover/Cover.jsx
  src/js/component/ProfilePageComponents/Cover/Cover.scss
  src/js/component/ProfilePageComponents/ProfileBiography/ProfileBiography.jsx
  src/js/component/ProfilePageComponents/ProfileBiography/ProfileBiography.scss
  src/js/component/ProfilePageComponents/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/component/ProfilePageComponents/ProfileCareerDescription/ProfileCareerDescription.scss
  src/js/component/ProfilePageComponents/ProfileClasses/ProfileClasses.jsx
  src/js/component/ProfilePageComponents/ProfileClasses/ProfileClasses.scss
  src/js/component/ProfilePageComponents/ProfileUserInfo/ProfileUserInfo.jsx
  src/js/component/ProfilePageComponents/ProfileUserInfo/ProfileUserInfo.scss
  src/js/component/ProfilePageComponents/Tags/InterestTag.jsx
  src/js/component/ProfilePageComponents/Tags/InterestTag.svg
  src/js/component/ProfilePageComponents/Tags/InterestTagStyled.scss
  src/js/component/StaticComponents/Buttons/Checkbox/Checkbox.jsx
  src/js/component/StaticComponents/Buttons/Checkbox/CheckboxStyles.scss
  src/js/layout.js
  src/js/views/HomePage/CalendarSideMenuDemo.png
  src/js/views/HomePage/HomePage.jsx
  src/js/views/HomePage/HomePage.scss
  src/js/views/LandingPage/LandingPage.jsx
  src/js/views/LandingPage/LandingPageStyles.scss
Labels: feature, work-in-progress, dont-merge

#33 Feature: View Profile
  src/js/component/ProfilePageComponents/Buttons/ProfileFavorite/ProfileFavorite.jsx
  src/js/component/ProfilePageComponents/Buttons/ProfileFavorite/ProfileFavorite.scss
  src/js/component/ProfilePageComponents/Cover/Cover.jsx
  src/js/component/ProfilePageComponents/Cover/Cover.scss
  src/js/component/ProfilePageComponents/ProfileBiography/ProfileBiography.jsx
  src/js/component/ProfilePageComponents/ProfileBiography/ProfileBiography.scss
  src/js/component/ProfilePageComponents/ProfileClasses/ProfileClasses.jsx
  src/js/component/ProfilePageComponents/ProfileUserInfo/ProfileUserInfo.jsx
  src/js/component/ProfilePageComponents/ProfileUserInfo/ProfileUserInfo.scss
  src/js/component/ProfilePageComponents/SocialMedia/SocialMedia.scss
  src/js/component/StaticComponents/Buttons/MyColls/MyColls.scss
  src/js/component/StaticComponents/Buttons/UCollLogo/UCOLLLogoHorizontal.png
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.css
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.css.map
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.jsx
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.scss
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogoVertical.png
  src/js/layout.js
  src/js/views/Profile/Profile.jsx
  src/js/views/Profile/ProfileStyles.scss
  src/js/views/Profile/ScrapProfileView/ScrapProfile.jsx
Labels: feature, ready-to-merge

#38 Feature: Buttons Ucoll logo
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.jsx
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.png
  src/js/component/StaticComponents/Buttons/UCollLogo/UCollLogo.scss
  src/js/component/StaticComponents/Buttons/UCollLogoHorizontal/UCOLLLogoHorizontal.png
  src/js/component/StaticComponents/Buttons/UCollLogoHorizontal/UCollLogoHorizontal.jsx
  src/js/component/StaticComponents/Buttons/UCollLogoHorizontal/UCollLogoHorizontal.scss
  src/js/component/StaticComponents/Navbar/Navbar.jsx
Labels: feature, ready-to-merge

#34 FIX: Convert Params To Props
  src/js/component/HomePageComponents/Coll/Coll.jsx
  src/js/component/HomePageComponents/Coll/Coll.scss
  src/js/component/HomePageComponents/Coll/CompressedColl/CompressedColl.jsx
  src/js/component/HomePageComponents/Coll/CompressedColl/CompressedColl.scss
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ClassesComponent/Classes.jsx
  src/js/component/HomePageComponents/Menus/ColleaguesSideMenu/ColleaguesSideMenu.jsx
  src/js/component/HomePageComponents/Menus/ProfileSideMenu/ProfileSideMenu.jsx
  src/js/component/HomePageComponents/Menus/Resources/Components/Resource.jsx
  src/js/component/HomePageComponents/Menus/Resources/ResourcesMenu.jsx
  src/js/component/MessagesComponents/MessageInfoButton/MessageInfoButton.jsx
  src/js/component/ProfilePageComponents/Cover/Cover.jsx
  src/js/component/ProfilePageComponents/ProfileBiography/ProfileBiography.jsx
  src/js/component/ProfilePageComponents/ProfileCareerDescription/ProfileCareerDescription.jsx
  src/js/component/ProfilePageComponents/ProfileClasses/ProfileClasses.jsx
  src/js/component/ProfilePageComponents/ProfileUserInfo/ProfileUserInfo.jsx
  src/js/component/ProfilePageComponents/SocialMedia/SocialMedia.jsx
  src/js/component/ProfilePageComponents/SocialMedia/SocialMediaText.jsx
  src/js/component/ProfilePageComponents/Tags/InterestTag.jsx
  src/js/component/StaticComponents/Buttons/Arrows/LeftArrow/LeftArrowButton.jsx
  src/js/component/StaticComponents/Buttons/Arrows/RightArrow/RightArrowButton.jsx
  src/js/component/StaticComponents/Buttons/CanButton/CanButton.jsx
  src/js/component/StaticComponents/Buttons/Favorite/Favorite.jsx
  src/js/component/StaticComponents/Buttons/Like/LikeButtons.jsx
  src/js/component/StaticComponents/Buttons/SearchBar/SearchBar.jsx
  src/js/component/StaticComponents/Portraits/Portrait/Portrait.jsx
  src/js/component/StaticComponents/Portraits/PortraitWithName/PortraitWithName.jsx
  src/js/component/footer.js
  src/js/component/navbar.js
  src/js/component/scrollToTop.js
  src/js/index.js
  src/js/layout.js
  src/js/views/HomePage/HomePage.jsx
  src/js/views/Profile/ScrapProfileView/ScrapProfile.jsx
  src/js/views/Profile/ScrapProfileView/ScrapProfileStyles.scss
Labels: bug, work-in-progress, dont-merge

#25 FEATURE: Coll constructor
  package-lock.json
  package.json
  src/js/component/CollConstructor/CollConstructor.jsx
  src/js/component/CollConstructor/CollConstructor.scss
  src/js/component/CollConstructor/ContentArea/ContentFile/ContentFile.jsx
  src/js/component/CollConstructor/ContentArea/ContentLink/ContentLink.jsx
  src/js/component/CollConstructor/ContentArea/ContentText/ContentText.jsx
  src/js/component/CollConstructor/ContentArea/ContentText/Toolbar.jsx
  src/js/component/CollConstructor/ContentArea/ContentText/ToolbarOptions.js
  src/js/component/CollConstructor/ContentArea/ContentText/tools.js
  src/js/component/StaticComponents/Buttons/NewPostButtons/NewPostPhoto.jsx
  src/js/layout.js
  src/styles/index.scss
Labels: feature, ready-to-merge

#39 Feature: Homepage/Coll/Tag Menu
  src/js/component/HomePageComponents/TagMenu/TagMenu.jsx
  src/js/component/HomePageComponents/TagMenu/TagMenu.scss
  src/js/component/StaticComponents/Buttons/TicketPost-It/TicketPostIt.jsx
  src/js/component/StaticComponents/Buttons/TicketPost-It/TicketPostItStyles.scss
  src/js/layout.js
Labels: feature, work-in-progress, dont-merge

#45 Feature/register bend connection
  package-lock.json
  package.json
  src/js/component/LandingPageComponents/RegisterSubviewComponents/RegisterCard/RegisterCard.jsx
  src/js/component/LandingPageComponents/RegisterSubviewComponents/RegisterCard/RegisterCardStyles.scss
  src/js/index.js
  src/js/layout.js
Labels: feature, ready-to-merge

#46 Feature/login sync with database
  src/js/component/LandingPageComponents/LogInCard/LoginCard.jsx
  src/js/layout.js
  src/js/store/appContext.js
  src/js/store/flux.js
Labels: feature, ready-to-merge
